server:
  port: 8001
spring:
  application:
    name: api-gateway

  spring:
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false
        routes:
          - id: CATEGORY-SERVICE
            uri: lb://CATEGORY-SERVICE
            predicates:
              - Path=/api/v1/category/**