# config-repo/application.yml
server:
  port: 0

spring:
  application:
    name: config-repo
  profiles:
    active: native

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
