app:
  name: "category Service"
  message: "Welcome to CategoryService!"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/categorydb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
